#!/bin/bash
#Create local multi-targets is exists in RELEASETOP
if [ -f "${RELEASETOP}/.SCRAM/${SCRAM_ARCH}/multi-targets" ] ; then
  MULTIARCH_TARGET=$(grep '^SCRAM_TARGET:=' ${RELEASETOP}/.SCRAM/${SCRAM_ARCH}/MakeData/variables.mk | sed 's|.*=||;s| ||g')
  if [ "${MULTIARCH_TARGET}" = "auto" ] ; then
    touch ${LOCALTOP}/.SCRAM/${SCRAM_ARCH}/multi-targets
  fi
fi
