#!/bin/bash
for mdir in tmp/${SCRAM_ARCH}/cxxmodules include/${SCRAM_ARCH}/cxxmodules ; do
  if [ -f "${LOCALTOP}/${mdir}/module.modulemap" ] ; then
    echo "RUNTIME:path:prepend:ROOT_INCLUDE_PATH=${basedir}/${mdir}"
    break
  fi
done

